const userTypes = {
  GET_OFFICIAL_VACATIONS_SUCCESS: "GET_OFFICIAL_VACATIONS_SUCCESS",
  GET_OFFICIAL_VACATIONS_LOADING: "GET_OFFICIAL_VACATIONS_LOADING",
  CREATE_APPLICANT_VACATION_SUCCESS: "CREATE_APPLICANT_VACATION_SUCCESS",
  CREATE_APPLICANT_VACATION_LOADING:"CREATE_APPLICANT_VACATION_LOADING"
};
export default userTypes;
