const orderHistory = {
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  ORDERS_LOADING: "ORDERS_LOADING",
  RATE_ORDER_SUCCESS: "RATE_ORDER_SUCCESS",
  RATE_ORDER_LOADING:"RATE_ORDER_LOADING"
};
export default orderHistory;
