const notifications = {
  GET_NOTIFICATIONS_SUCCESS: "GET_NOTIFICATIONS_SUCCESS",
  GET_PAGINATION_SUCCESS: "GET_PAGINATION_SUCCESS",
  GET_PAGINATION_LOADING: "GET_PAGINATION_LOADING",
  NOTIFICATIONS_LOADING: "NOTIFICATIONS_LOADING",
};
export default notifications;
